export const AuthConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
  
    SIGNUP_REQUEST: "SIGNUP_REQUEST",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_FAILURE: "SIGNUP_FAILURE",
  };

  export const DoctorConstants={
   ADD_DOCTOR_REQUEST:"ADD_DOCTOR_REQUEST",
   ADD_DOCTOR_SUCCESS:"ADD_DOCTOR_SUCCESS",
   ADD_DOCTOR_FAILURE:"ADD_DOCTOR_FAILURE",

   GET_DOCTOR_REQUEST:"GET_DOCTOR_REQUEST",
   GET_DOCTOR_SUCCESS:"GET_DOCTOR_SUCCESS",
   GET_DOCTOR_FAILURE:"GET_DOCTOR_FAILURE",
  }

  export const AppointmentConstants = {
    ADD_APPOINTMENT_REQUEST: "ADD_APPOINTMENT_REQUEST",
    ADD_APPOINTMENT_SUCCESS: "ADD_APPOINTMENT_SUCCESS",
    ADD_APPOINTMENT_FAILURE: "ADD_APPOINTMENT_FAILURE",
  
    GET_APPOINTMENT_REQUEST: "GET_APPOINTMENT_REQUEST",
    GET_APPOINTMENT_SUCCESS: "GET_APPOINTMENT_SUCCESS",
    GET_APPOINTMENT_FAILURE: "GET_APPOINTMENT_FAILURE",

    DELETE_APPOINTMENT_REQUEST: "DELETE_APPOINTMENT_REQUEST",
    DELETE_APPOINTMENT_SUCCESS: "DELETE_APPOINTMENT_SUCCESS",
    DELETE_APPOINTMENT_FAILURE: "DELETE_APPOINTMENT_FAILURE",
  };

  export const DentalCheckupConstants = {
    ADD_CHECKUP_REQUEST: "ADD_CHECKUP_REQUEST",
    ADD_CHECKUP_SUCCESS: "ADD_CHECKUP_SUCCESS",
    ADD_CHECKUP_FAILURE: "ADD_CHECKUP_FAILURE",

    GET_CHECKUP_REQUEST: "GET_CHECKUP_REQUEST",
    GET_CHECKUP_SUCCESS: "GET_CHECKUP_SUCCESS",
    GET_CHECKUP_FAILURE: "GET_CHECKUP_FAILURE",

    
    DELETE_CHECKUP_REQUEST: "DELETE_CHECKUP_REQUEST",
    DELETE_CHECKUP_SUCCESS: "DELETE_CHECKUP_SUCCESS",
    DELETE_CHECKUP_FAILURE: "DELETE_CHECKUP_FAILURE",
  };


  
 export const CheckupAppointmentConstants={
  ADMIN_GET_CHECKUPAPPOINTMENT_REQUEST:"ADMIN_GET_CHECKUPAPPOINTMENT_REQUEST",
  ADMIN_GET_CHECKUPAPPOINTMENT_SUCCESS:"ADMIN_GET_CHECKUPAPPOINTMENT_SUCCESS",
  ADMIN_GET_CHECKUPAPPOINTMENT_FAILURE:"ADMIN_GET_CHECKUPAPPOINTMENT_FAILURE",

    DELETE_CHECKUPAPPOINTMENT_REQUEST: "DELETE_CHECKUPAPPOINTMENT_REQUEST",
    DELETE_CHECKUPAPPOINTMENT_SUCCESS: "DELETE_CHECKUPAPPOINTMENT_SUCCESS",
    DELETE_CHECKUPAPPOINTMENT_FAILURE: "DELETE_CHECKUPAPPOINTMENT_FAILURE",
 }