export const AuthConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
  
    SIGNUP_REQUEST: "SIGNUP_REQUEST",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_FAILURE: "SIGNUP_FAILURE",
  };

  export const DoctorConstants={
   ADD_DOCTOR_REQUEST:"ADD_DOCTOR_REQUEST",
   ADD_DOCTOR_SUCCESS:"ADD_DOCTOR_SUCCESS",
   ADD_DOCTOR_FAILURE:"ADD_DOCTOR_FAILURE",

   GET_DOCTOR_REQUEST:"GET_DOCTOR_REQUEST",
   GET_DOCTOR_SUCCESS:"GET_DOCTOR_SUCCESS",
   GET_DOCTOR_FAILURE:"GET_DOCTOR_FAILURE",
  }